name: Cache Demo
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prime-cache-d4db335
      id: cache-d4db335
      uses: actions/cache@v4
      with:
        key: cache-d4db335
        path: .
    - name: Echo cache result
      run: echo "Cache hit: ${{ steps.cache-d4db335.outputs.cache-hit }}"
